### ISSUE TITLE
set-state与set-output需要更新

### ISSUE THREAD

**Issue by thanatos1111** [gooin/DailySync#24]
运行自动同步时，到了Run stefanzweifel/git-auto-commit-action@v4 这一步，显示以下warning：

`Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
`

应该是需要更新下package
> Action authors who are using the toolkit should update the @actions/core package to v1.10.0 or greater to get the updated saveState and setOutput functions.

**Comment by gooin** [comment]
按文档更新了，您可以更新代码后看看还有这个warning吗

**Comment by gooin** [comment]
作者已修复
