### ISSUE TITLE
请问下这个包是什么@gooin/garmin-connect

### ISSUE THREAD

**Issue by Likenttt** [gooin/DailySync#3]
const { GarminConnect } = require('@gooin/garmin-connect-cn');
const { GarminConnect: GarminConnectGlobal } = require('@gooin/garmin-connect');

是否可以查看源代码做了些什么？把账号密码传进去有一定担忧

**Comment by gooin** [comment]
源码在我repo下，实现对中国区佳明API的操作。 https://github.com/gooin/garmin-connect-cn

**Comment by gooin** [comment]
> const { GarminConnect } = require('@gooin/garmin-connect-cn'); const { GarminConnect: GarminConnectGlobal } = require('@gooin/garmin-connect');
> 
> 是否可以查看源代码做了些什么？把账号密码传进去有一定担忧
源码在我repo下，实现对中国区佳明API的操作。 https://github.com/gooin/garmin-connect-cn
