### ISSUE TITLE
国际区新账号没有数据时执行异常

### ISSUE THREAD

**Issue by gooin** [gooin/DailySync#5]
```bash
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'startTimeLocal' of undefined
```

**Comment by keepup** [comment]
@gooin 
如果海外区是新账号，globalActs[0] 会是 undefine， 依然会报错，应该修改为：
const latestGlobalActStartTime = globalActs[0]?.startTimeLocal ?? '0';

**Comment by gooin** [comment]
> @gooin 如果海外区是新账号，globalActs[0] 会是 undefine， 依然会报错，应该修改为： const latestGlobalActStartTime = globalActs[0]?.startTimeLocal ?? '0';

感谢提醒，已修复
